/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ClerkPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DbToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DbUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleAiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HouseApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InngestEventKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InngestSigningKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ListingLab": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PublicGoogleApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripePublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZipCodeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
